[package]
name = "hello_world"
version = "0.0.1"

[dependencies]
Sui = { local = "C:/Users/lizhiheng/.move/https___github_com_MystenLabs_sui_git_framework__testnet/crates/sui-framework/packages/sui-framework" } 



[addresses]
hello_world =  "0x0"
